### ISSUE TITLE
Dell EMC Networking Ansible Roles Name are wrong.

### ISSUE THREAD

**Issue by tydice** [Dell-Networking/ansible-dellos-docs#1]
In Installation > Control Machine Page, the format of ansible roles name is like "Dell-Networking.dellos.aaa". 
But it should be modified as "Dell-Networking.dellos-aaa" for all role names to download from ansible galaxy properly.

**Comment by skg-net** [comment]
@DoHyeongPark  Thanks for reporting the issue, we are working on the same.

**Comment by skg-net** [comment]
fixed in https://github.com/Dell-Networking/ansible-dellos-docs/commit/ef74d02e941f811355d57ba7f55cf6b171671fbe
