### ISSUE TITLE
Feature Request: ansible network_cli support

### ISSUE THREAD

**Issue by ryanmerolle** [Dell-Networking/ansible-dellos-docs#13]
@abirami-n 

Per the recent push towards a standardized ansible network automation it would be good that this module was updated to follow this new approach.

https://www.ansible.com/blog/red-hat-ansible-network-automation-updates
https://docs.ansible.com/ansible/latest/plugins/connection/network_cli.html
https://docs.ansible.com/ansible/latest/network/user_guide/network_best_practices_2.5.html

**Comment by skg-net** [comment]
@ryanmerolle network_cli is already supported, can you please be more specific what features you are looking for and which OS? [OS6/OS9/OS10/OPX]

**Comment by ryanmerolle** [comment]
It was missing from https://docs.ansible.com/ansible/latest/network/user_guide/platform_index.html

But I later found in the module code that it was supported.  I should have closed this earlier.
